#! /usr/bin/env sh
SEARCHTERM="$1"
docker run -d --restart always --name alpine-apk-search -t alpine-xen-iso sh 1>/dev/null 2>/dev/null
docker exec -i -t alpine-apk-search sh -c "apk update && apk search $SEARCHTERM"
docker rm -f alpine-apk-search 1>/dev/null 2>/dev/null
